name: notify of pull_request creation
on:
  pull_request_target:
    types: [ opened ]
    branches:
      - main

jobs:
  notify:
    uses: osscameroon/global-github-actions/.github/workflows/notify_on_pull_request_open.yaml@main
    secrets:
      telegram_channel_id: ${{ secrets.TELEGRAM_OSSCAMEROON_CHANNEL_ID }}
      telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}